package com.zeze.demo.mybatis.auto;

import java.util.Date;

public class TAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.user_id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.user_pw
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    private String userPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.reg_time
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.user_id
     *
     * @return the value of t_account.user_id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.user_id
     *
     * @param userId the value for t_account.user_id
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.user_pw
     *
     * @return the value of t_account.user_pw
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public String getUserPw() {
        return userPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.user_pw
     *
     * @param userPw the value for t_account.user_pw
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public void setUserPw(String userPw) {
        this.userPw = userPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.reg_time
     *
     * @return the value of t_account.reg_time
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.reg_time
     *
     * @param regTime the value for t_account.reg_time
     *
     * @mbggenerated Mon May 30 12:28:39 GMT+08:00 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}